site_name: Peter Larsson's HPC Notes
theme:
  name: material
  font:
    text: Noto Sans
    code: IBM Plex Mono
  icon:
    logo: material/server
  palette:
    primary: red
  features:
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.tabs
  plugins:
    - privacy
extra:
    generator: false
extra_css:
    - stylesheets/extra.css
markdown_extensions:
  - tables
nav:
  - Home: index.md
  - How-to guides:
    - Compiling CP2K 2023.1 with AMD GPU support: howto/cp2k-lumi.md
  - Benchmarks:
    - CP2K on LUMI: benchmarks/cp2k-lumi.md
  - Reference:
    - MI250x: reference/mi250x.md
    - ROCm: reference/rocm.md

